/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciaviajes.presentacion;

import agenciaviajes.negocio.Cliente;
import agenciaviajes.negocio.GestorClientes;
import agenciaviajes.utils.Utilidades;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author Usuario
 */
public class GUIEstadisticaPorSexoGrafica extends javax.swing.JFrame implements AView {
    
    public GUIEstadisticaPorSexoGrafica() {
        initComponents();
        setSize(245, 420);
        setLocation(1000, 50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hombres = new javax.swing.JPanel();
        pgbBarraHombres = new javax.swing.JProgressBar();
        Mujeres = new javax.swing.JPanel();
        pgbBarraMujeres = new javax.swing.JProgressBar();
        txtHombresMujeres = new javax.swing.JLabel();
        txtPromedioHombres = new javax.swing.JLabel();
        txtPromedioMujeres = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hombres.setBackground(new java.awt.Color(255, 255, 255));
        Hombres.setToolTipText("");
        Hombres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Hombres.setName(""); // NOI18N
        Hombres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pgbBarraHombres.setBackground(new java.awt.Color(255, 255, 255));
        pgbBarraHombres.setMaximum(300);
        pgbBarraHombres.setOrientation(1);
        pgbBarraHombres.setToolTipText("");
        Hombres.add(pgbBarraHombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 300));

        getContentPane().add(Hombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 100, 300));
        Hombres.getAccessibleContext().setAccessibleName("");

        Mujeres.setBackground(new java.awt.Color(255, 255, 255));
        Mujeres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pgbBarraMujeres.setBackground(new java.awt.Color(255, 255, 255));
        pgbBarraMujeres.setMaximum(300);
        pgbBarraMujeres.setOrientation(1);
        pgbBarraMujeres.setToolTipText("");
        Mujeres.add(pgbBarraMujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 300));

        getContentPane().add(Mujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 39, 100, 300));

        txtHombresMujeres.setText("Hombres                       Mujeres");
        getContentPane().add(txtHombresMujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 180, -1));

        txtPromedioHombres.setText("ext");
        getContentPane().add(txtPromedioHombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtPromedioMujeres.setText("ext");
        getContentPane().add(txtPromedioMujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void graficar(ArrayList<Cliente> clientes) {
        setVisible(true);
        int h = 0, m = 0;
        for (Cliente cli : clientes) {
            if(cli.getSexo().equals("Masculino")){
                h++;
            }
            if(cli.getSexo().equals("Femenino")){
                m++;
            }
        }
	int promHombres = (h*100)/(h+m);
	int promMujeres = (m*100)/(h+m);
        
	txtPromedioHombres.setText(promHombres+"%");
	txtPromedioMujeres.setText(promMujeres+"%");
        pgbBarraHombres.setValue(300-((300*promMujeres)/100));
        pgbBarraMujeres.setValue(300-((300*promHombres)/100));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hombres;
    private javax.swing.JPanel Mujeres;
    private javax.swing.JProgressBar pgbBarraHombres;
    private javax.swing.JProgressBar pgbBarraMujeres;
    private javax.swing.JLabel txtHombresMujeres;
    private javax.swing.JLabel txtPromedioHombres;
    private javax.swing.JLabel txtPromedioMujeres;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {
        try {
            GestorClientes gestor = (GestorClientes) amodel;
            ArrayList<Cliente> listado = gestor.consultarClientes();
            graficar(listado);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIClientesVer.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeError("Error al crear la Grafica", "Atención");
        } 
    }
}
